/*
 * This file was generated by micropython-extmod-generator
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2020 
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */


#define MODULE_CONSTS_ENABLED (1) // you may copy this line to the mpconfigport.h
#if MODULE_CONSTS_ENABLED

// Include required definitions first.
#include "py/obj.h"
#include "py/objstr.h"
#include "py/objtuple.h"
#include "py/runtime.h"
#include "py/builtin.h"

#include "objfloat.h"

    /*
    // Example exception for any generated function
    if (some_val == 0) {
        mp_raise_ValueError("'some_val' can't be zero!");
    }
    */

// Module constants declarations
STATIC const bool *CONST_BOOL0 = MP_ROM_FALSE;
STATIC const bool *CONST_BOOL1 = MP_ROM_TRUE;
STATIC const MP_DEFINE_FLOAT_OBJ(CONST_FLOAT_float_obj, 5.5);
STATIC const mp_int_t CONST_INT = 99;
STATIC const void *CONST_NONE = MP_ROM_NONE;
STATIC const MP_DEFINE_STR_OBJ(CONST_STR_str_obj, "-1aaa");

const mp_rom_obj_tuple_t CONST_TUPLE_1_1_tuple_obj = {{&mp_type_tuple}, 3, {
    MP_ROM_INT(10),
    MP_ROM_INT(20),
    MP_ROM_INT(30),
},};

const mp_rom_obj_tuple_t CONST_TUPLE_2_9_tuple_obj = {{&mp_type_tuple}, 5, {
    MP_ROM_INT(100),
    MP_ROM_INT(200),
    MP_ROM_TRUE,
    MP_ROM_NONE,
    MP_ROM_FALSE,
},};
STATIC const MP_DEFINE_STR_OBJ(CONST_TUPLE_1_1_str_obj, "22qq44");
STATIC const MP_DEFINE_STR_OBJ(CONST_TUPLE_1_7_str_obj, "33ww66");
STATIC const MP_DEFINE_STR_OBJ(CONST_TUPLE_1_8_str_obj, "-1aaa");
const mp_rom_obj_tuple_t CONST_TUPLE_1_11_tuple_obj = {{&mp_type_tuple}, 10, {
    MP_ROM_INT(1),
    MP_ROM_PTR(&CONST_TUPLE_1_1_str_obj),
    MP_ROM_TRUE,
    MP_ROM_NONE,
    MP_ROM_FALSE,
    MP_ROM_FALSE,
    MP_ROM_INT(11),
    MP_ROM_PTR(&CONST_TUPLE_1_7_str_obj),
    MP_ROM_PTR(&CONST_TUPLE_1_8_str_obj),
    MP_ROM_PTR(&CONST_TUPLE_2_9_tuple_obj),
},};
STATIC const MP_DEFINE_STR_OBJ(CONST_TUPLE_0_2_str_obj, "22qq");
STATIC const MP_DEFINE_FLOAT_OBJ(CONST_TUPLE_0_8_float_obj, 11.11);
STATIC const MP_DEFINE_STR_OBJ(CONST_TUPLE_0_9_str_obj, "33ww");
STATIC const MP_DEFINE_STR_OBJ(CONST_TUPLE_0_10_str_obj, "-1aaa");
const mp_rom_obj_tuple_t CONST_TUPLE_0_6_tuple_obj = {{&mp_type_tuple}, 12, {
    MP_ROM_INT(1),
    MP_ROM_PTR(&CONST_TUPLE_1_1_tuple_obj),
    MP_ROM_PTR(&CONST_TUPLE_0_2_str_obj),
    MP_ROM_TRUE,
    MP_ROM_NONE,
    MP_ROM_FALSE,
    MP_ROM_FALSE,
    MP_ROM_INT(11),
    MP_ROM_PTR(&CONST_TUPLE_0_8_float_obj),
    MP_ROM_PTR(&CONST_TUPLE_0_9_str_obj),
    MP_ROM_PTR(&CONST_TUPLE_0_10_str_obj),
    MP_ROM_PTR(&CONST_TUPLE_1_11_tuple_obj),
},};

const mp_rom_obj_tuple_t CONST_TUPLE_X_1_2_tuple_obj = {{&mp_type_tuple}, 3, {
    MP_ROM_INT(-10),
    MP_ROM_INT(-20),
    MP_ROM_INT(-30),
},};
STATIC const MP_DEFINE_FLOAT_OBJ(CONST_TUPLE_X_0_1_float_obj, 7.77);
const mp_rom_obj_tuple_t CONST_TUPLE_X_0_7_tuple_obj = {{&mp_type_tuple}, 3, {
    MP_ROM_INT(-1),
    MP_ROM_PTR(&CONST_TUPLE_X_0_1_float_obj),
    MP_ROM_PTR(&CONST_TUPLE_X_1_2_tuple_obj),
},};


// Defining module functions
// def test_test()
STATIC mp_obj_t mod_consts_test_test(void) {
    // TODO
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(mod_consts_test_test_obj, mod_consts_test_test);

// Defining classes
// class WithConsts(object):
typedef struct _mp_obj_WithConsts_t {
    mp_obj_base_t base;
} mp_obj_WithConsts_t;

// WithConsts constants
STATIC const bool *WithConsts_CONST_BOOL0 = MP_ROM_FALSE;
STATIC const bool *WithConsts_CONST_BOOL1 = MP_ROM_TRUE;
STATIC const MP_DEFINE_FLOAT_OBJ(WithConsts_CONST_FLOAT_float_obj, 5.5);
STATIC const mp_int_t WithConsts_CONST_INT = 99;
STATIC const void *WithConsts_CONST_NONE = MP_ROM_NONE;
STATIC const MP_DEFINE_STR_OBJ(WithConsts_CONST_STR_str_obj, "-1aaa");

const mp_rom_obj_tuple_t WithConsts_CONST_TUPLE_1_2_tuple_obj = {{&mp_type_tuple}, 3, {
    MP_ROM_INT(10),
    MP_ROM_INT(20),
    MP_ROM_INT(30),
},};

const mp_rom_obj_tuple_t WithConsts_CONST_TUPLE_2_9_tuple_obj = {{&mp_type_tuple}, 5, {
    MP_ROM_INT(100),
    MP_ROM_INT(200),
    MP_ROM_TRUE,
    MP_ROM_NONE,
    MP_ROM_FALSE,
},};
STATIC const MP_DEFINE_STR_OBJ(WithConsts_CONST_TUPLE_1_1_str_obj, "22qq44");
STATIC const MP_DEFINE_STR_OBJ(WithConsts_CONST_TUPLE_1_7_str_obj, "33ww66");
STATIC const MP_DEFINE_STR_OBJ(WithConsts_CONST_TUPLE_1_8_str_obj, "-1aaa");
const mp_rom_obj_tuple_t WithConsts_CONST_TUPLE_1_12_tuple_obj = {{&mp_type_tuple}, 10, {
    MP_ROM_INT(1),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_1_1_str_obj),
    MP_ROM_TRUE,
    MP_ROM_NONE,
    MP_ROM_FALSE,
    MP_ROM_FALSE,
    MP_ROM_INT(11),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_1_7_str_obj),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_1_8_str_obj),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_2_9_tuple_obj),
},};
STATIC const MP_DEFINE_STR_OBJ(WithConsts_CONST_TUPLE_0_3_str_obj, "22qq");
STATIC const MP_DEFINE_FLOAT_OBJ(WithConsts_CONST_TUPLE_0_9_float_obj, 11.11);
STATIC const MP_DEFINE_STR_OBJ(WithConsts_CONST_TUPLE_0_10_str_obj, "33ww");
STATIC const MP_DEFINE_STR_OBJ(WithConsts_CONST_TUPLE_0_11_str_obj, "-1aaa");
const mp_rom_obj_tuple_t WithConsts_CONST_TUPLE_0_6_tuple_obj = {{&mp_type_tuple}, 13, {
    MP_ROM_INT(-1),
    MP_ROM_INT(1),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_1_2_tuple_obj),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_0_3_str_obj),
    MP_ROM_TRUE,
    MP_ROM_NONE,
    MP_ROM_FALSE,
    MP_ROM_FALSE,
    MP_ROM_INT(11),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_0_9_float_obj),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_0_10_str_obj),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_0_11_str_obj),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_1_12_tuple_obj),
},};

const mp_rom_obj_tuple_t WithConsts_CONST_TUPLE_X_1_3_tuple_obj = {{&mp_type_tuple}, 3, {
    MP_ROM_INT(-10),
    MP_ROM_INT(-20),
    MP_ROM_INT(-30),
},};
STATIC const MP_DEFINE_FLOAT_OBJ(WithConsts_CONST_TUPLE_X_0_2_float_obj, 7.77);
const mp_rom_obj_tuple_t WithConsts_CONST_TUPLE_X_0_7_tuple_obj = {{&mp_type_tuple}, 4, {
    MP_ROM_INT(-2),
    MP_ROM_INT(-1),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_X_0_2_float_obj),
    MP_ROM_PTR(&WithConsts_CONST_TUPLE_X_1_3_tuple_obj),
},};

STATIC const mp_int_t WithConsts_ESP_ERR_FLASH_BASE = 24576;
STATIC const mp_int_t WithConsts_ESP_ERR_INVALID_ARG = 258;
STATIC const mp_int_t WithConsts_ESP_ERR_INVALID_CRC = 265;
STATIC const mp_int_t WithConsts_ESP_ERR_INVALID_MAC = 267;
STATIC const mp_int_t WithConsts_ESP_ERR_INVALID_RESPONSE = 264;
STATIC const mp_int_t WithConsts_ESP_ERR_INVALID_SIZE = 260;
STATIC const mp_int_t WithConsts_ESP_ERR_INVALID_STATE = 259;
STATIC const mp_int_t WithConsts_ESP_ERR_INVALID_VERSION = 266;
STATIC const mp_int_t WithConsts_ESP_ERR_MESH_BASE = 16384;
STATIC const mp_int_t WithConsts_ESP_ERR_NOT_FOUND = 261;
STATIC const mp_int_t WithConsts_ESP_ERR_NOT_SUPPORTED = 262;
STATIC const mp_int_t WithConsts_ESP_ERR_NO_MEM = 257;
STATIC const mp_int_t WithConsts_ESP_ERR_TIMEOUT = 263;
STATIC const mp_int_t WithConsts_ESP_ERR_WIFI_BASE = 12288;

// Defining WithConsts methods
// def WithConsts.test_test(self)
STATIC mp_obj_t mod_consts_WithConsts_test_test(mp_obj_t self) {
    // TODO
    return mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_consts_WithConsts_test_test_obj, mod_consts_WithConsts_test_test);

// WithConsts stuff
STATIC const mp_rom_map_elem_t mod_consts_WithConsts_locals_dict_table[] = {
    { MP_ROM_QSTR(MP_QSTR_test_test), MP_ROM_PTR(&mod_consts_WithConsts_test_test_obj) },
    { MP_ROM_QSTR(MP_QSTR_CONST_BOOL0), MP_ROM_FALSE },
    { MP_ROM_QSTR(MP_QSTR_CONST_BOOL1), MP_ROM_TRUE },
    { MP_ROM_QSTR(MP_QSTR_CONST_FLOAT), MP_ROM_PTR(&WithConsts_CONST_FLOAT_float_obj) },
    { MP_ROM_QSTR(MP_QSTR_CONST_INT), MP_ROM_INT(99) },
    { MP_ROM_QSTR(MP_QSTR_CONST_NONE), MP_ROM_NONE },
    { MP_ROM_QSTR(MP_QSTR_CONST_STR), MP_ROM_PTR(&WithConsts_CONST_STR_str_obj) },
    { MP_ROM_QSTR(MP_QSTR_CONST_TUPLE), MP_ROM_PTR(&WithConsts_CONST_TUPLE_0_6_tuple_obj) },
    { MP_ROM_QSTR(MP_QSTR_CONST_TUPLE_X), MP_ROM_PTR(&WithConsts_CONST_TUPLE_X_0_7_tuple_obj) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_FLASH_BASE), MP_ROM_INT(24576) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_INVALID_ARG), MP_ROM_INT(258) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_INVALID_CRC), MP_ROM_INT(265) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_INVALID_MAC), MP_ROM_INT(267) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_INVALID_RESPONSE), MP_ROM_INT(264) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_INVALID_SIZE), MP_ROM_INT(260) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_INVALID_STATE), MP_ROM_INT(259) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_INVALID_VERSION), MP_ROM_INT(266) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_MESH_BASE), MP_ROM_INT(16384) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_NOT_FOUND), MP_ROM_INT(261) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_NOT_SUPPORTED), MP_ROM_INT(262) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_NO_MEM), MP_ROM_INT(257) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_TIMEOUT), MP_ROM_INT(263) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ERR_WIFI_BASE), MP_ROM_INT(12288) },
};
STATIC MP_DEFINE_CONST_DICT(mod_consts_WithConsts_locals_dict, mod_consts_WithConsts_locals_dict_table);

STATIC const mp_obj_type_t mod_consts_WithConsts_type = {
    { &mp_type_type },
    .name = MP_QSTR_WithConsts,
    .locals_dict = (void*)&mod_consts_WithConsts_locals_dict,
};


// Set up the module properties
STATIC const mp_rom_map_elem_t mod_consts_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_consts) },
    { MP_ROM_QSTR(MP_QSTR_test_test), MP_ROM_PTR(&mod_consts_test_test_obj) },
    { MP_ROM_QSTR(MP_QSTR_WithConsts), MP_ROM_PTR(&mod_consts_WithConsts_type) },
    { MP_ROM_QSTR(MP_QSTR_CONST_BOOL0), MP_ROM_FALSE },
    { MP_ROM_QSTR(MP_QSTR_CONST_BOOL1), MP_ROM_TRUE },
    { MP_ROM_QSTR(MP_QSTR_CONST_FLOAT), MP_ROM_PTR(&CONST_FLOAT_float_obj) },
    { MP_ROM_QSTR(MP_QSTR_CONST_INT), MP_ROM_INT(99) },
    { MP_ROM_QSTR(MP_QSTR_CONST_NONE), MP_ROM_NONE },
    { MP_ROM_QSTR(MP_QSTR_CONST_STR), MP_ROM_PTR(&CONST_STR_str_obj) },
    { MP_ROM_QSTR(MP_QSTR_CONST_TUPLE), MP_ROM_PTR(&CONST_TUPLE_0_6_tuple_obj) },
    { MP_ROM_QSTR(MP_QSTR_CONST_TUPLE_X), MP_ROM_PTR(&CONST_TUPLE_X_0_7_tuple_obj) },
};
STATIC MP_DEFINE_CONST_DICT(mod_consts_globals, mod_consts_globals_table);

// Define the module object
const mp_obj_module_t mod_consts_cmodule = {
    .base = { &mp_type_module },
    //.name = MP_QSTR_consts, // absent
    .globals = (mp_obj_dict_t*)&mod_consts_globals,
};
// Register the module
MP_REGISTER_MODULE(MP_QSTR_consts, mod_consts_cmodule, MODULE_CONSTS_ENABLED);

#endif // MODULE_CONSTS_ENABLED
